djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
]

djangoproject/quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'
urlpatterns = [
    path('', views.main, name='index'),
    path('<int:page>', views.main, name='root_paginate'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    #path('admin/', views.main, name='root'),
]

djangoproject/users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views


app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('password_reset/', 
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html',
             email_template_name='users/password_reset_email.html',
             success_url=reverse_lazy('users:password_reset_done')
         ),
         name='password_reset'),
    
    # URL для підтвердження про надсилання листа для скидання паролю
    path('password_reset/done/', 
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    
    # URL для підтвердження нового паролю
    path('reset/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html',
             success_url=reverse_lazy('users:password_reset_complete')
         ),
         name='password_reset_confirm'),
    
    # URL для підтвердження успішного скидання паролю
    path('reset/done/', 
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

djangoproject/quotes/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)

class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

djangoproject/users/models.py
from django.db import models

# Create your models here.

djangoproject/quotes/forms.py
from django import forms
from .models import Author, Quote

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']

    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['author'].label_from_instance = lambda obj: "%s" % obj.fullname
            self.fields['tags'].label_from_instance = lambda obj: "%s" % obj.name

djangoproject/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

djangoproject/quotes/views.py
from django.shortcuts import render, redirect
from .utils import get_mongodb
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .forms import AuthorForm, QuoteForm

# Create your views here.
def main(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page =paginator.page(page)
    return render(request, "quotes/index.html", context={'quotes':quotes_on_page})

@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('authors:main')  
    else:
        form = AuthorForm()
    return render(request, 'quotes/add_author.html', {'form': form})

@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quotes:main')  
    else:
        form = QuoteForm()
    return render(request, 'quotes/add_quote.html', {'form': form})

djangoproject/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserRegisterForm, UserLoginForm
from django.contrib.auth.views import LoginView, PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('users:login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm

# Rename UserLoginView to user_login for URL mapping
user_login = UserLoginView.as_view()


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

djangoproject/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}
  <h2>Add author</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

djangoproject/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}
  <h2>Add quote</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

djangoproject/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}" />

    <title>Homework</title>
  </head>
  <body>
    <div class="container">
      <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
          <h1>
            <a href="/" style="text-decoration: none">Quotes to Scrape</a>
          </h1>
        </div>
        <div class="col-md-4">
          <p>
              <a href="{% url 'users:register' %}" class="btn btn-primary">SignUp</a>
              <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
              <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
          </p>
          {% if user.is_authenticated %}
              <div style="margin-top: 20px;"> 
                  <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add New Author</a>
                  <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add New Quote</a>
              </div>
          {% endif %}
      </div>
      </div>

      {% block content %} {% endblock %}
    </div>
  </body>
</html>

djangoproject/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}
{% block content %}

<div class="row">
  <div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">{{ quote.quote }}</span>
      <span>by
        <small class="author" itemprop="author">{{ quote.author|author }}</small>
        <a href="/author/{{ quote.author }}">(about)</a>
      </span>
      <div class="tags">
        Tags: {% for tag in quote.tags %}
        <a class="tag" href="/tag/{{ tag }}">{{ tag }}</a>
        {% endfor %}
      </div>
    </div>
    {% endfor %}

    <ul class="pager">
      <li class="previous">
        <a class="{% if not quotes.has_previous %} disabled {% endif %}"
           href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
          <span aria-hidden="true">←</span>Previous</a>
      </li>
      <li class="next">
        <a class="{% if not quotes.has_next %} disabled {% endif %}"
           href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
          Next <span aria-hidden="true">→</span></a>
      </li>
    </ul>
  </div>
</div>

{% endblock %}

djangoproject/users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}
  <h2>Login</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
  
  <p><a href="{% url 'users:password_reset' %}">Forgot password?</a></p>

{% endblock %}

djangoproject/users/templates/users/password_reset.html
<!-- templates/users/password_reset.html -->

{% extends "quotes/base.html" %}
{% block content %}
  <h2>Reset Your Password</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset Password</button>
  </form>
{% endblock %}

djangoproject/users/templates/users/password_reset_complete.html
<!-- templates/users/password_reset_complete.html -->

{% extends "quotes/base.html" %}
{% block content %}
  <h2>Password Reset Successfully</h2>
  <p>Your password has been successfully reset. You can now <a href="{% url 'users:login' %}">log in</a> with your new password.</p>
{% endblock %}

djangoproject/users/templates/users/password_reset_confirm.html
<!-- templates/users/registration/password_reset_confirm.html -->

{% extends "quotes/base.html" %}
{% block content %}
  <h2>Enter New Password</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Set New Password</button>
  </form>
{% endblock %}

djangoproject/users/templates/users/password_reset_done.html
<!-- users/templates/users/password_reset_done.html -->
{% extends "quotes/base.html" %}
{% block content %}
  <h2>Password reset sent</h2>
  <p>We have emailed you instructions for setting your password. If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
{% endblock %}

djangoproject/users/templates/users/password_reset_email.html
<!-- templates/users/password_reset_email.html -->
{% autoescape off %}
Hi {{ user.get_username }},

You're receiving this email because you requested a password reset for your user account at {{ site_name }}.

Please go to the following page and choose a new password:
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

Your username, in case you've forgotten: {{ user.get_username }}

Thanks for using our site!

The {{ site_name }} team
{% endautoescape %}

djangoproject/users/templates/users/register.html
{% extends "quotes/base.html" %}
{% block content %}
  <h2>Register</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
{% endblock %}